/**
 * CSS Generator utility
 *
 * Converts theme objects to CSS variables and complete CSS files.
 */

import type { Theme, ThemeColors, ThemeTypography, ThemeLayout, ThemeSpacing } from '../types/theme';

/**
 * Generate CSS variables from theme colors
 */
export function generateColorCSS(colors: ThemeColors): string {
  return `  /* Brand Colors */
  --color-primary: ${colors.primary};
  --color-secondary: ${colors.secondary};
  --color-accent: ${colors.accent};
  --color-success: ${colors.success};
  --color-warning: ${colors.warning};
  --color-error: ${colors.error};
  --color-info: ${colors.info};

  /* Background Colors */
  --color-background-primary: ${colors.background.primary};
  --color-background-secondary: ${colors.background.secondary};
  --color-background-tertiary: ${colors.background.tertiary};
  --color-background-elevated: ${colors.background.elevated};
  --color-background-overlay: ${colors.background.overlay};

  /* Text Colors */
  --color-text-primary: ${colors.text.primary};
  --color-text-secondary: ${colors.text.secondary};
  --color-text-tertiary: ${colors.text.tertiary};
  --color-text-disabled: ${colors.text.disabled};
  --color-text-inverse: ${colors.text.inverse};

  /* Border Colors */
  --color-border-default: ${colors.border.default};
  --color-border-subtle: ${colors.border.subtle};
  --color-border-strong: ${colors.border.strong};`;
}

/**
 * Generate CSS variables from theme typography
 */
export function generateTypographyCSS(typography: ThemeTypography): string {
  return `  /* Font Families */
  --font-family-heading: ${typography.fontFamily.heading};
  --font-family-body: ${typography.fontFamily.body};
  --font-family-mono: ${typography.fontFamily.mono};

  /* Font Sizes */
  --font-size-xs: ${typography.fontSize.xs};
  --font-size-sm: ${typography.fontSize.sm};
  --font-size-base: ${typography.fontSize.base};
  --font-size-lg: ${typography.fontSize.lg};
  --font-size-xl: ${typography.fontSize.xl};
  --font-size-2xl: ${typography.fontSize['2xl']};
  --font-size-3xl: ${typography.fontSize['3xl']};
  --font-size-4xl: ${typography.fontSize['4xl']};

  /* Font Weights */
  --font-weight-light: ${typography.fontWeight.light};
  --font-weight-normal: ${typography.fontWeight.normal};
  --font-weight-medium: ${typography.fontWeight.medium};
  --font-weight-semibold: ${typography.fontWeight.semibold};
  --font-weight-bold: ${typography.fontWeight.bold};

  /* Line Heights */
  --line-height-tight: ${typography.lineHeight.tight};
  --line-height-normal: ${typography.lineHeight.normal};
  --line-height-relaxed: ${typography.lineHeight.relaxed};

  /* Letter Spacing */
  --letter-spacing-tight: ${typography.letterSpacing.tight};
  --letter-spacing-normal: ${typography.letterSpacing.normal};
  --letter-spacing-wide: ${typography.letterSpacing.wide};`;
}

/**
 * Generate CSS variables from theme layout
 */
export function generateLayoutCSS(layout: ThemeLayout): string {
  return `  /* Border Radius */
  --border-radius-none: ${layout.borderRadius.none};
  --border-radius-sm: ${layout.borderRadius.sm};
  --border-radius-md: ${layout.borderRadius.md};
  --border-radius-lg: ${layout.borderRadius.lg};
  --border-radius-xl: ${layout.borderRadius.xl};
  --border-radius-full: ${layout.borderRadius.full};

  /* Shadows */
  --shadow-sm: ${layout.shadow.sm};
  --shadow-md: ${layout.shadow.md};
  --shadow-lg: ${layout.shadow.lg};
  --shadow-xl: ${layout.shadow.xl};

  /* Transitions */
  --transition-fast: ${layout.transition.fast};
  --transition-normal: ${layout.transition.normal};
  --transition-slow: ${layout.transition.slow};

  /* Z-Index */
  --z-dropdown: ${layout.zIndex.dropdown};
  --z-sticky: ${layout.zIndex.sticky};
  --z-fixed: ${layout.zIndex.fixed};
  --z-modal: ${layout.zIndex.modal};
  --z-popover: ${layout.zIndex.popover};
  --z-tooltip: ${layout.zIndex.tooltip};`;
}

/**
 * Generate CSS variables from theme spacing
 */
export function generateSpacingCSS(spacing: ThemeSpacing): string {
  const scale = spacing.scale;
  return `  /* Spacing Base */
  --spacing-base: ${spacing.base};

  /* Spacing Scale */
  --spacing-0: ${scale[0]};
  --spacing-1: ${scale[1]};
  --spacing-2: ${scale[2]};
  --spacing-3: ${scale[3]};
  --spacing-4: ${scale[4]};
  --spacing-5: ${scale[5]};
  --spacing-6: ${scale[6]};
  --spacing-8: ${scale[8]};
  --spacing-10: ${scale[10]};
  --spacing-12: ${scale[12]};
  --spacing-16: ${scale[16]};
  --spacing-20: ${scale[20]};
  --spacing-24: ${scale[24]};
  --spacing-32: ${scale[32]};
  --spacing-40: ${scale[40]};
  --spacing-48: ${scale[48]};
  --spacing-64: ${scale[64]};`;
}

/**
 * Generate complete CSS from theme
 */
export function generateCSSFromTheme(theme: Theme): string {
  return `/**
 * ${theme.name}
 * ${theme.description}
 *
 * Generated by Vue Theme Switcher
 */

:root {
${generateColorCSS(theme.colors)}

${generateTypographyCSS(theme.typography)}

${generateSpacingCSS(theme.spacing)}

${generateLayoutCSS(theme.layout)}
}`;
}

/**
 * Generate CSS with font import
 */
export function generateCSSWithFontImport(theme: Theme): string {
  let fontImport = '';

  if (theme.fontConfig) {
    const { family, weights, subsets, display } = theme.fontConfig;
    fontImport = `@import url('https://fonts.googleapis.com/css2?family=${family.replace(' ', '+')}:wght@${weights.join(';')}&subset=${subsets.join(',')}&display=${display || 'swap'}');

`;
  }

  return fontImport + generateCSSFromTheme(theme);
}

/**
 * Format timestamp for filename
 */
export function formatTimestampForFilename(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hours = String(now.getHours()).padStart(2, '0');
  const minutes = String(now.getMinutes()).padStart(2, '0');
  const seconds = String(now.getSeconds()).padStart(2, '0');

  return `${year}${month}${day}-${hours}${minutes}${seconds}`;
}
